/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java`
    `maven`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.0")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.0")
    testImplementation("org.mockito:mockito-core:3.3.0")
    testImplementation("org.mockito:mockito-junit-jupiter:3.5.13")
}

group = "org.commandline"
version = "1.0-SNAPSHOT"
description = "hackassembler"
java.sourceCompatibility = JavaVersion.VERSION_11

sourceSets.main{                                
        java.srcDirs("src/main/java")
}
sourceSets.test {
        java.srcDirs("src/test/java")
}

tasks.withType<Test> {
  useJUnitPlatform()
}

val jar by tasks.getting(Jar::class) {
    manifest {
        attributes["Main-Class"] = "org.commandline.hackassembler.Assembler"
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
